Repository mfrade13/ClasesInfografia, pull requests merged in 2019-10, with the labels that each got.

#1 Update readme file
  tareas/Consigna.txt
  tareas/README.md
Labels: production

#9 Sergio
  memoryGame/MemoryGame/.DS_Store
  memoryGame/MemoryGame/1.png
  memoryGame/MemoryGame/10.png
  memoryGame/MemoryGame/11.png
  memoryGame/MemoryGame/12.png
  memoryGame/MemoryGame/13.png
  memoryGame/MemoryGame/14.png
  memoryGame/MemoryGame/15.png
  memoryGame/MemoryGame/16.png
  memoryGame/MemoryGame/17.png
  memoryGame/MemoryGame/18.png
  memoryGame/MemoryGame/2.png
  memoryGame/MemoryGame/3.png
  memoryGame/MemoryGame/4.png
  memoryGame/MemoryGame/5.png
  memoryGame/MemoryGame/6.png
  memoryGame/MemoryGame/7.png
  memoryGame/MemoryGame/8.png
  memoryGame/MemoryGame/9.png
  memoryGame/MemoryGame/Icon-167.png
  memoryGame/MemoryGame/Icon-60.png
  memoryGame/MemoryGame/Icon-60@2x.png
  memoryGame/MemoryGame/Icon-60@3x.png
  memoryGame/MemoryGame/Icon-72.png
  memoryGame/MemoryGame/Icon-72@2x.png
  memoryGame/MemoryGame/Icon-76.png
  memoryGame/MemoryGame/Icon-76@2x.png
  memoryGame/MemoryGame/Icon-Small-40.png
  memoryGame/MemoryGame/Icon-Small-40@2x.png
  memoryGame/MemoryGame/Icon-Small-50.png
  memoryGame/MemoryGame/Icon-Small-50@2x.png
  memoryGame/MemoryGame/Icon-Small.png
  memoryGame/MemoryGame/Icon-Small@2x.png
  memoryGame/MemoryGame/Icon-Small@3x.png
  memoryGame/MemoryGame/Icon-hdpi.png
  memoryGame/MemoryGame/Icon-ldpi.png
  memoryGame/MemoryGame/Icon-mdpi.png
  memoryGame/MemoryGame/Icon-xhdpi.png
  memoryGame/MemoryGame/Icon-xxhdpi.png
  memoryGame/MemoryGame/Icon-xxxhdpi.png
  memoryGame/MemoryGame/Icon.png
  memoryGame/MemoryGame/Icon@2x.png
  memoryGame/MemoryGame/build.settings
  memoryGame/MemoryGame/config.lua
  memoryGame/MemoryGame/main.lua
  memoryGame/MemoryGame/menu.jpg
Labels: production, project

#10 Clase 10 de animacion de camaras
  Clase10/Icon-hdpi.png
  Clase10/Icon-ldpi.png
  Clase10/Icon-mdpi.png
  Clase10/Icon-xhdpi.png
  Clase10/Icon-xxhdpi.png
  Clase10/Icon-xxxhdpi.png
  Clase10/Icon.png
  Clase10/Images.xcassets/AppIcon.appiconset/Contents.json
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-1024.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-120.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-152.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-167.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-180.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-40.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-58.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-76.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-80.png
  Clase10/Images.xcassets/AppIcon.appiconset/Icon-87.png
  Clase10/Images.xcassets/Contents.json
  Clase10/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
  Clase10/LaunchScreen.storyboardc/Info.plist
  Clase10/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
  Clase10/LaunchScreen.storyboardc/designable.storyboard
  Clase10/build.settings
  Clase10/comic2.png
  Clase10/config.lua
  Clase10/hoja_comic.png
  Clase10/main.lua
Labels: documentation
